#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 13 23:40:41 2019

@author: moby

"""

headers_ABNB = {
'authority': 'www.airbnb.com',
'method': 'GET',
'scheme': 'https',
'accept': 'application/json, text/javascript, */*; q=0.01',
'accept-encoding': 'gzip, deflate, br',
'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
'cache-control': 'no-cache',
'pragma': 'no-cache',
'referer': 'https://www.airbnb.com/s/Bali--Indonesia/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJoQ8Q6NNB0S0RkOYkS7EPkSQ&query=Bali%2C%20Indonesia&search_type=FILTER_CHANGE&allow_override%5B%5D=&s_tag=ReRM3Y7C',
'save-data': 'on',
'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36',
'x-csrf-token': 'V4$.airbnb.com$V5KUmGhJ0AQ$yjbviXB2lQjGp5qffckUt_0dU4TTOiQrQ-ZL9OsFBCM=',
'x-requested-with': 'XMLHttpRequest'}
          
headers_BC = {
'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36',
}


cookies_ABNB = [

{
    "domain": ".airbnb.com",
    "expirationDate": 1681737949,
    "hostOnly": False,
    "httpOnly": False,
    "name": "__ssid",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "9a77d4f875e8b1a1fd2b648ee5fd22a",
    "id": 1
},
{
    "domain": ".airbnb.com",
    "hostOnly": False,
    "httpOnly": False,
    "name": "_csrf_token",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": True,
    "session": True,
    "storeId": "0",
    "value": "V4%24.airbnb.com%24dN13wEHJP_4%24XsS_EwO1no4EuZBqFD6AwZqmXO6l96TqSFoSiNlZ9T8%3D",
    "id": 2
},
{
    "domain": ".airbnb.com",
    "expirationDate": 1618580193,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_ga",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "GA1.2.831629397.1555507545",
    "id": 3
},
{
    "domain": ".airbnb.com",
    "expirationDate": 1555508219,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_gat",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "1",
    "id": 4
},
{
    "domain": ".airbnb.com",
    "expirationDate": 1563283543,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_gcl_au",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "1.1.1574903772.1555507544",
    "id": 5
},
{
    "domain": ".airbnb.com",
    "expirationDate": 1555594593,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_gid",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "GA1.2.357214443.1555507545",
    "id": 6
},
{
    "domain": ".airbnb.com",
    "expirationDate": 1618666591.089186,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_user_attributes",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": True,
    "session": False,
    "storeId": "0",
    "value": "%7B%22curr%22%3A%22USD%22%2C%22guest_exchange%22%3A1.0%2C%22device_profiling_session_id%22%3A%221555507540--ffaefd3172eb3f604656bb3b%22%2C%22giftcard_profiling_session_id%22%3A%221555507540--64f8a03aea60fc6682174fad%22%2C%22reservation_profiling_session_id%22%3A%221555507540--944567ff702bfb730299a70e%22%7D",
    "id": 7
},
{
    "domain": ".airbnb.com",
    "expirationDate": 1560691539.692679,
    "hostOnly": False,
    "httpOnly": False,
    "name": "016951b48",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "control",
    "id": 8
},
{
    "domain": ".airbnb.com",
    "expirationDate": 1555511145,
    "hostOnly": False,
    "httpOnly": False,
    "name": "AMP_TOKEN",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "%24NOT_FOUND",
    "id": 9
},
{
    "domain": ".airbnb.com",
    "expirationDate": 1618580193.008681,
    "hostOnly": False,
    "httpOnly": False,
    "name": "bev",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": True,
    "session": False,
    "storeId": "0",
    "value": "1555507539_eGXiTYqxAYNy%2F3rp",
    "id": 10
},
{
    "domain": ".airbnb.com",
    "hostOnly": False,
    "httpOnly": False,
    "name": "cache_state",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": True,
    "session": True,
    "storeId": "0",
    "value": "0",
    "id": 11
},
{
    "domain": ".airbnb.com",
    "expirationDate": 1641821793,
    "hostOnly": False,
    "httpOnly": False,
    "name": "cbkp",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "3",
    "id": 12
},
{
    "domain": ".airbnb.com",
    "expirationDate": 1560691539.69252,
    "hostOnly": False,
    "httpOnly": False,
    "name": "cdn_exp_c93eb6109a0d84ec9",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "control",
    "id": 13
},
{
    "domain": ".airbnb.com",
    "hostOnly": False,
    "httpOnly": False,
    "name": "flags",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": True,
    "session": True,
    "storeId": "0",
    "value": "0",
    "id": 14
},
{
    "domain": ".airbnb.com",
    "expirationDate": 1555593941.298075,
    "hostOnly": False,
    "httpOnly": False,
    "name": "jitney_client_session_created_at",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": True,
    "session": False,
    "storeId": "0",
    "value": "1555507541",
    "id": 15
},
{
    "domain": ".airbnb.com",
    "expirationDate": 1555593941.297925,
    "hostOnly": False,
    "httpOnly": False,
    "name": "jitney_client_session_id",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": True,
    "session": False,
    "storeId": "0",
    "value": "2c6fc2ba-1145-4bae-8699-8dd160d6efdf",
    "id": 16
},
{
    "domain": ".airbnb.com",
    "expirationDate": 1555594593.990368,
    "hostOnly": False,
    "httpOnly": False,
    "name": "jitney_client_session_updated_at",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": True,
    "session": False,
    "storeId": "0",
    "value": "1555508193",
    "id": 17
},
{
    "domain": ".airbnb.com",
    "expirationDate": 1560691599.24248,
    "hostOnly": False,
    "httpOnly": False,
    "name": "pwatb_exp",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "85",
    "id": 18
},
{
    "domain": ".airbnb.com",
    "expirationDate": 2185894381,
    "hostOnly": False,
    "httpOnly": False,
    "name": "sdid",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": True,
    "session": False,
    "storeId": "0",
    "value": "",
    "id": 19
},
{
    "domain": "www.airbnb.com",
    "hostOnly": True,
    "httpOnly": False,
    "name": "currency",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "USD",
    "id": 20
}
]

cookies_BC = [
{
    "domain": ".booking.com",
    "expirationDate": 1566620638,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_gcl_au",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "1.1.1327154546.1558844638",
    "id": 1
},
{
    "domain": ".booking.com",
    "expirationDate": 1558844978,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_px3",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "62746765e0538e756c1583a44ce3af0e39b3569fb16a15b3f7841ab1fbb677d4:Jzkg1ajx2fRsITTfWFk53r/UMl2miSHdHkBW37+pbBoGgv0bZwWczF+cAbwGqvRZlN9WfCqltHZZxmkBxIh1dw==:1000:Qkg/uT1VFv3QQpFSQYuQh7+XYXaNTlS3XPa2fEJ4GsMT31cFSYNSPkRVeKs56n0rmT0RrLiumwCYtei2mtPoo5ePgEQrirfCXzd4yp+vD2lAuM3UKitx9G0+DfL2fe05kH8qFkfxa11WGqWEJ3nzuonv8KBaqmb3HYsBzi+gYmw=",
    "id": 2
},
{
    "domain": ".booking.com",
    "expirationDate": 1558844985,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_pxde",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "fbf183bab7daea76f43427a567196f0b50517263897c988d64dc53b6b783d3fb:eyJ0aW1lc3RhbXAiOjE1NTg4NDQ2NTQ5MDcsImlwY19pZCI6W119",
    "id": 3
},
{
    "domain": ".booking.com",
    "expirationDate": 1605500647,
    "hostOnly": False,
    "httpOnly": False,
    "name": "_pxvid",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "1a0dbf5b-7f6e-11e9-8aa9-0242ac120008",
    "id": 4
},
{
    "domain": ".booking.com",
    "expirationDate": 1558931039.063253,
    "hostOnly": False,
    "httpOnly": True,
    "name": "BJS",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": True,
    "session": False,
    "storeId": "0",
    "value": "-",
    "id": 5
},
{
    "domain": ".booking.com",
    "expirationDate": 1716524645.417057,
    "hostOnly": False,
    "httpOnly": True,
    "name": "bkng",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": True,
    "session": False,
    "storeId": "0",
    "value": "11UmFuZG9tSVYkc2RlIyh9Yaa29%2F3xUOLbbmD9q%2B5pe3UosD9L9kzKRuGxqe83%2Fk%2BEC2x%2BDJZcN5d1JmyqfbDQw1Q3Sx6hhn%2F%2F%2F5bAREmqqeqodpCTDTeBqtpRt2qHBNV77gMEj1cJCkIBuK3p7DLkfcHP5h%2B1pWuKJw5ktvxbWp1SgI1Em4zUmx3AvTbC%2B3HCai3c2cLxybA%3D",
    "id": 6
},
{
    "domain": ".booking.com",
    "expirationDate": 1590380636,
    "hostOnly": False,
    "httpOnly": False,
    "name": "cors_js",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "1",
    "id": 7
},
{
    "domain": ".booking.com",
    "expirationDate": 1593008648,
    "hostOnly": False,
    "httpOnly": False,
    "name": "cto_lwid",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "6e5bfee0-cb3b-474b-957c-a6c30dc83998",
    "id": 8
},
{
    "domain": ".booking.com",
    "hostOnly": False,
    "httpOnly": False,
    "name": "lastSeen",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "1558844664432",
    "id": 9
},
{
    "domain": ".booking.com",
    "expirationDate": 1590380645,
    "hostOnly": False,
    "httpOnly": False,
    "name": "utag_main",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "v_id:016af261a2080002d5ff5531cffa03079008007100838$_sn:1$_ss:1$_st:1558846445898$ses_id:1558844645898%3Bexp-session$_pn:1%3Bexp-session$4split:2$4split2:1",
    "id": 10
},
{
    "domain": ".booking.com",
    "expirationDate": 1574569445,
    "hostOnly": False,
    "httpOnly": False,
    "name": "zz_cook_tms_ed",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "1",
    "id": 11
},
{
    "domain": ".booking.com",
    "expirationDate": 1590294245,
    "hostOnly": False,
    "httpOnly": False,
    "name": "zz_cook_tms_seg1",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "1",
    "id": 12
},
{
    "domain": ".booking.com",
    "expirationDate": 1561436646,
    "hostOnly": False,
    "httpOnly": False,
    "name": "zz_cook_tms_seg3",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "5",
    "id": 13
},
{
    "domain": "www.booking.com",
    "hostOnly": True,
    "httpOnly": False,
    "name": "header_signin_prompt",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": True,
    "storeId": "0",
    "value": "1",
    "id": 14
},
{
    "domain": "www.booking.com",
    "expirationDate": 1561523037,
    "hostOnly": True,
    "httpOnly": False,
    "name": "vpmss",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": False,
    "session": False,
    "storeId": "0",
    "value": "1",
    "id": 15
}
]

tags_BC={ 
        'id':'data-hotelid',
        'name':'sr-hotel__name',
        'kind':'sr-hotel__type',
        'price_format':'price',
        'cur':'price',
        'price':'price',
        'd_price':'price',
        'room_type':'room_link',
        'extras':'sr_room_reinforcement',
        'mark':'bui-review-score__badge',
        'n_reviews':'bui-review-score__text',
        'n_lookers':'sr_no_desc_users',
        'demand':'rollover-s1',
        'demand3':'rollover-s2',
        'area3':'sr_card_address_line',
        'area':'distfromdest',
        'area2':'pub_trans',
        'max_pax':'bui-u-sr-only',
        'room_size':'sr-rt-size',
        'address':'address',
        'link':'hotel_name_link',
        'stars':'bk-icon-wrapper',
        'promo':'bk-icon -iconset-thumbs_up',
        'promo2':'ranking_vb_tag',
        'sleep_arrang':'bui-u-full-width',
        'lonlat':'115'}

#run self.filter_codes() to get an updated dict
filter_codes_BC = {

        'ht_id': ['Villas', 'Guesthouses', 'Hotels', 'Homestays', 'Holidayparks', 'Resorts', 'Bedandbreakfasts', 'Hostels', 'Apartments', 'Holidayhomes', 'Lodges', 'Campsites', 'Countryhouses', 'Luxurytents', 'Boats', 'Capsulehotels', 'Farmstays', 'Economyhotels', 'Motels'], 
        'concise_unit_type': [], 'class': ['1 star', '2 stars', '3 stars', '4 stars', '5 stars', 'Unrated'],
        'popular_activities': ['Massage', 'Bicycle rental (additional charge)', 'Diving', 'Hiking', 'Cycling'], 
        'hr_24': ['Front desk open 24/7'], 'ht_beach': ['Beachfront'], 
        'popular_nearby_landmarks': ['Ubud Market', 'Ubud Palace', 'Lotus Cafe', 'Sarong Restaurant', 'Bebek Bengil', 'Ku De Ta', 'Ubud Monkey Forest', 'Bridges Restaurant', 'Potato Head Beach Club', 'Metis Restaurant', 'Kuta Square', 'Legian Art Market', 'Batu Jimbar Café', 'Poppies Lane 1', 'Hard Rock Cafe', 'Poppies Lane 2', 'Vue Beach Club', 'Echo Beach', 'Mushroom Bay', 'Dream Beach', 'Sky Garden', 'Cocoon Beach Club', 'Le Mayeur Museum', 'Jimbaran Corner', 'Padang Padang Beach', 'Yellow Bridge', 'Padangbai Bay', 'Pasifika Museum', 'Bali Collection', 'Elephant Cave', 'Blue Lagoon', 'Geger Beach', 'Uluwatu Temple', 'Lake Batur', 'Krisna Funtastic Land', 'Gamat Bay', 'Bebek Bengil Nusa Dua', 'Pandawa Beach', 'The Rock Bar', 'Krisna Water Sports', 'Pulaki Temple', 'Bali Museum', 'Aling Aling Waterfall', 'Bali Zoo', 'Tanah Lot Temple', 'Art Centre', 'Sekumpul Waterfall', 'Goa Giri Putri Temple', 'Atuh Beach', 'Kintamani', 'Tegenungan Waterfall', "Angel's Billabong"], 
        'review_score': ['Superb: 9+', 'Very good: 8+', 'Good: 7+', 'Pleasant: 6+', 'No rating'], 
        'hotelfacility': ['Parking', 'Restaurant', 'Pets allowed', 'Room service', 'Fitness centre', 'Non-smoking rooms', 'Airport shuttle', 'Facilities for disabled guests', 'Family rooms', 'Spa and wellness centre', 'BBQ facilities', 'Free WiFi', 'Electric vehicle charging station', 'Swimming pool'],
        'uf': ['Ubud', 'Seminyak', 'Canggu', 'Sanur', 'Kuta', 'Jimbaran', 'Uluwatu', 'NusaLembongan', 'Legian', 'Denpasar', 'NusaPenida', 'NusaDua', 'Amed', 'Lovina', 'Kerobokan', 'Pemuteran', 'Candidasa', 'Tabanan', 'Munduk', 'Gianyar', 'Sidemen', 'TanahLot', 'Tejakula', 'Tegalalang', 'Kintamani','Tulamben'],
        'accessible_facilities': ['Wheelchair accessible', 'Toilet with grab rails', 'Higher level toilet', 'Lower bathroom sink', 'Emergency cord in bathroom', 'Visual aids: Braille', 'Visual aids: Tactile signs', 'Auditory guidance'], 
        'chaincode': ['Airy Rooms', 'Aston International Hotels, Resorts & Residences', 'Avilla Hospitality', 'Elite Havens', 'HARRIS Hotels & Resorts', 'RedDoorz', 'Santika Indonesia Hotels & Resorts', 'Swiss-Belhotel International', 'ZEN Premium', 'ZEN Rooms'], 
        'accessible_room_facilities': ['Entire unit located on ground floor', 'Upper floors accessible by lift', 'Entire unit wheelchair accessible', 'Toilet with grab rails', 'Adapted bath', 'Roll in shower', 'Walk in shower', 'Raised toilet', 'Lowered sink', 'Emergency cord in bathroom', 'Shower chair']}


FTF_codes_uf = ['-2701757',
  '900040134',
  '900048236',
  '325646',
  '-2683839',
  '-2680135',
  '325689',
  '-2684938',
  '900048191',
  '900052009',
  '-2676772',
  '900040039',
  '-2670300',
  '-2697286',
  '900048179',
  '900048175',
  '900048235',
  '-2698644',
  '-2688600',
  '-2678309',
  '-2696826',
  '-2682745',
  '-2700056',
  '900048238',
  '-2699992',
  '900048374']
FTF_names_uf = ['Ubud',
  'Seminyak',
  'Canggu',
  'Sanur',
  'Kuta',
  'Jimbaran',
  'Uluwatu',
  'NusaLembongan',
  'Legian',
  'NusaPenida',
  'Denpasar',
  'NusaDua',
  'Amed',
  'Lovina',
  'Kerobokan',
  'Pemuteran',
  'Candidasa',
  'Tabanan',
  'Munduk',
  'Gianyar',
  'Sidemen',
  'Kintamani',
  'Tejakula',
  'TanahLot',
  'Tegalalang',
  'Singaraja']
FTF_quantity_uf = [1964,
  1496,
  1069,
  477,
  456,
  443,
  387,
  363,
  349,
  296,
  291,
  252,
  232,
  211,
  201,
  96,
  92,
  78,
  65,
  63,
  52,
  47,
  46,
  42,
  41,
  40]
FTF_codes_ht_id = ['216',
  '213',
  '204',
  '222',
  '212',
  '206',
  '208',
  '203',
  '201',
  '220',
  '221',
  '214',
  '223',
  '224',
  '215',
  '210',
  '225',
  '231',
  '205',
  '228']

FTF_names_ht_id =  ['Guesthouses',
  'Villas',
  'Hotels',
  'Homestays',
  'Holidayparks',
  'Resorts',
  'Bedandbreakfasts',
  'Hostels',
  'Apartments',
  'Holidayhomes',
  'Lodges',
  'Campsites',
  'Countryhouses',
  'Luxurytents',
  'Boats',
  'Farmstays',
  'Capsulehotels',
  'Economyhotels',
  'Motels',
  'Chalets']

FTF_quantity_ht_id = [1888,
  1557,
  1137,
  669,
  413,
  391,
  233,
  215,
  136,
  74,
  59,
  21,
  11,
  10,
  7,
  4,
  4,
  3,
  2,
  1]

