#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 13 23:40:41 2019

@author: moby

"""

headers_ABNB = {
'authority': 'www.airbnb.com',
'method': 'GET',
'scheme': 'https',
'accept': 'application/json, text/javascript, */*; q=0.01',
'accept-encoding': 'gzip, deflate, br',
'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
'cache-control': 'no-cache',
'pragma': 'no-cache',
'referer': 'https://www.airbnb.com/s/Bali--Indonesia/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJoQ8Q6NNB0S0RkOYkS7EPkSQ&query=Bali%2C%20Indonesia&search_type=FILTER_CHANGE&allow_override%5B%5D=&s_tag=ReRM3Y7C',
'save-data': 'on',
'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36',
'x-csrf-token': 'V4$.airbnb.com$V5KUmGhJ0AQ$yjbviXB2lQjGp5qffckUt_0dU4TTOiQrQ-ZL9OsFBCM=',
'x-requested-with': 'XMLHttpRequest'}
          
headers_BC = {
'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36',
}


cookies_ABNB = None ##Please insert your own cookies

tags_BC={ 
        'id':'data-hotelid',
        'name':'sr-hotel__name',
        'kind':'sr-hotel__type',
        'price_format':'price',
        'cur':'price',
        'price':'price',
        'd_price':'price',
        'room_type':'room_link',
        'extras':'sr_room_reinforcement',
        'mark':'bui-review-score__badge',
        'n_reviews':'bui-review-score__text',
        'n_lookers':'sr_no_desc_users',
        'demand':'rollover-s1',
        'demand3':'rollover-s2',
        'area3':'sr_card_address_line',
        'area':'distfromdest',
        'area2':'pub_trans',
        'max_pax':'bui-u-sr-only',
        'room_size':'sr-rt-size',
        'address':'address',
        'link':'hotel_name_link',
        'stars':'bk-icon-wrapper',
        'promo':'bk-icon -iconset-thumbs_up',
        'promo2':'ranking_vb_tag',
        'sleep_arrang':'bui-u-full-width',
        'lonlat':'115'}

#run self.filter_codes() to get an updated dict
filter_codes_BC = {

        'ht_id': ['Villas', 'Guesthouses', 'Hotels', 'Homestays', 'Holidayparks', 'Resorts', 'Bedandbreakfasts', 'Hostels', 'Apartments', 'Holidayhomes', 'Lodges', 'Campsites', 'Countryhouses', 'Luxurytents', 'Boats', 'Capsulehotels', 'Farmstays', 'Economyhotels', 'Motels'], 
        'concise_unit_type': [], 'class': ['1 star', '2 stars', '3 stars', '4 stars', '5 stars', 'Unrated'],
        'popular_activities': ['Massage', 'Bicycle rental (additional charge)', 'Diving', 'Hiking', 'Cycling'], 
        'hr_24': ['Front desk open 24/7'], 'ht_beach': ['Beachfront'], 
        'popular_nearby_landmarks': ['Ubud Market', 'Ubud Palace', 'Lotus Cafe', 'Sarong Restaurant', 'Bebek Bengil', 'Ku De Ta', 'Ubud Monkey Forest', 'Bridges Restaurant', 'Potato Head Beach Club', 'Metis Restaurant', 'Kuta Square', 'Legian Art Market', 'Batu Jimbar Café', 'Poppies Lane 1', 'Hard Rock Cafe', 'Poppies Lane 2', 'Vue Beach Club', 'Echo Beach', 'Mushroom Bay', 'Dream Beach', 'Sky Garden', 'Cocoon Beach Club', 'Le Mayeur Museum', 'Jimbaran Corner', 'Padang Padang Beach', 'Yellow Bridge', 'Padangbai Bay', 'Pasifika Museum', 'Bali Collection', 'Elephant Cave', 'Blue Lagoon', 'Geger Beach', 'Uluwatu Temple', 'Lake Batur', 'Krisna Funtastic Land', 'Gamat Bay', 'Bebek Bengil Nusa Dua', 'Pandawa Beach', 'The Rock Bar', 'Krisna Water Sports', 'Pulaki Temple', 'Bali Museum', 'Aling Aling Waterfall', 'Bali Zoo', 'Tanah Lot Temple', 'Art Centre', 'Sekumpul Waterfall', 'Goa Giri Putri Temple', 'Atuh Beach', 'Kintamani', 'Tegenungan Waterfall', "Angel's Billabong"], 
        'review_score': ['Superb: 9+', 'Very good: 8+', 'Good: 7+', 'Pleasant: 6+', 'No rating'], 
        'hotelfacility': ['Parking', 'Restaurant', 'Pets allowed', 'Room service', 'Fitness centre', 'Non-smoking rooms', 'Airport shuttle', 'Facilities for disabled guests', 'Family rooms', 'Spa and wellness centre', 'BBQ facilities', 'Free WiFi', 'Electric vehicle charging station', 'Swimming pool'],
        'uf': ['Ubud', 'Seminyak', 'Canggu', 'Sanur', 'Kuta', 'Jimbaran', 'Uluwatu', 'NusaLembongan', 'Legian', 'Denpasar', 'NusaPenida', 'NusaDua', 'Amed', 'Lovina', 'Kerobokan', 'Pemuteran', 'Candidasa', 'Tabanan', 'Munduk', 'Gianyar', 'Sidemen', 'TanahLot', 'Tejakula', 'Tegalalang', 'Kintamani','Tulamben'],
        'accessible_facilities': ['Wheelchair accessible', 'Toilet with grab rails', 'Higher level toilet', 'Lower bathroom sink', 'Emergency cord in bathroom', 'Visual aids: Braille', 'Visual aids: Tactile signs', 'Auditory guidance'], 
        'chaincode': ['Airy Rooms', 'Aston International Hotels, Resorts & Residences', 'Avilla Hospitality', 'Elite Havens', 'HARRIS Hotels & Resorts', 'RedDoorz', 'Santika Indonesia Hotels & Resorts', 'Swiss-Belhotel International', 'ZEN Premium', 'ZEN Rooms'], 
        'accessible_room_facilities': ['Entire unit located on ground floor', 'Upper floors accessible by lift', 'Entire unit wheelchair accessible', 'Toilet with grab rails', 'Adapted bath', 'Roll in shower', 'Walk in shower', 'Raised toilet', 'Lowered sink', 'Emergency cord in bathroom', 'Shower chair']}


FTF_codes_uf = ['-2701757',
  '900040134',
  '900048236',
  '325646',
  '-2683839',
  '-2680135',
  '325689',
  '-2684938',
  '900048191',
  '900052009',
  '-2676772',
  '900040039',
  '-2670300',
  '-2697286',
  '900048179',
  '900048175',
  '900048235',
  '-2698644',
  '-2688600',
  '-2678309',
  '-2696826',
  '-2682745',
  '-2700056',
  '900048238',
  '-2699992',
  '900048374']
FTF_names_uf = ['Ubud',
  'Seminyak',
  'Canggu',
  'Sanur',
  'Kuta',
  'Jimbaran',
  'Uluwatu',
  'NusaLembongan',
  'Legian',
  'NusaPenida',
  'Denpasar',
  'NusaDua',
  'Amed',
  'Lovina',
  'Kerobokan',
  'Pemuteran',
  'Candidasa',
  'Tabanan',
  'Munduk',
  'Gianyar',
  'Sidemen',
  'Kintamani',
  'Tejakula',
  'TanahLot',
  'Tegalalang',
  'Singaraja']
FTF_quantity_uf = [1964,
  1496,
  1069,
  477,
  456,
  443,
  387,
  363,
  349,
  296,
  291,
  252,
  232,
  211,
  201,
  96,
  92,
  78,
  65,
  63,
  52,
  47,
  46,
  42,
  41,
  40]
FTF_codes_ht_id = ['216',
  '213',
  '204',
  '222',
  '212',
  '206',
  '208',
  '203',
  '201',
  '220',
  '221',
  '214',
  '223',
  '224',
  '215',
  '210',
  '225',
  '231',
  '205',
  '228']

FTF_names_ht_id =  ['Guesthouses',
  'Villas',
  'Hotels',
  'Homestays',
  'Holidayparks',
  'Resorts',
  'Bedandbreakfasts',
  'Hostels',
  'Apartments',
  'Holidayhomes',
  'Lodges',
  'Campsites',
  'Countryhouses',
  'Luxurytents',
  'Boats',
  'Farmstays',
  'Capsulehotels',
  'Economyhotels',
  'Motels',
  'Chalets']

FTF_quantity_ht_id = [1888,
  1557,
  1137,
  669,
  413,
  391,
  233,
  215,
  136,
  74,
  59,
  21,
  11,
  10,
  7,
  4,
  4,
  3,
  2,
  1]

